import moment from "moment";

export default function validateDateTimeInput(str) {
  str = str.trim().replace(/[-/]/g, " ");

  return moment(
    str,
    [
      "D M",
      "HA D M",
      "Ha D M",
      "D M HA",
      "D M Ha",
      "H:m D M",
      "H:ma D M",
      "H:mA D M",
      "D M H:m",
      "D M H:ma",
      "D M H:mA",
      "D MMM",
      "HA D MMM",
      "Ha D MMM",
      "D MMM HA",
      "D MMM Ha",
      "H:m D MMM",
      "H:ma D MMM",
      "H:mA D MMM",
      "D MMM H:m",
      "D MMM H:ma",
      "D MMM H:mA",
      "M D",
      "HA M D",
      "Ha M D",
      "M D HA",
      "M D Ha",
      "H:m M D",
      "H:ma M D",
      "H:mA M D",
      "M D H:m",
      "M D H:ma",
      "M D H:mA",
      "MMM D",
      "HA MMM D",
      "Ha MMM D",
      "MMM D HA",
      "MMM D Ha",
      "H:m MMM D",
      "H:ma MMM D",
      "H:mA MMM D",
      "MMM D H:m",
      "MMM D H:ma",
      "MMM D H:mA",
      "D M YYYY",
      "HA D M YYYY",
      "Ha D M YYYY",
      "D M YYYY HA",
      "D M YYYY Ha",
      "H:m D M YYYY",
      "H:ma D M YYYY",
      "H:mA D M YYYY",
      "D M YYYY H:m",
      "D M YYYY H:ma",
      "D M YYYY H:mA",
      "D MMM YYYY",
      "HA D MMM YYYY",
      "Ha D MMM YYYY",
      "D MMM YYYY HA",
      "D MMM YYYY Ha",
      "H:m D MMM YYYY",
      "H:ma D MMM YYYY",
      "H:mA D MMM YYYY",
      "D MMM YYYY H:m",
      "D MMM YYYY H:ma",
      "D MMM YYYY H:mA",
      "M D YYYY",
      "HA M D YYYY",
      "Ha M D YYYY",
      "M D YYYY HA",
      "M D YYYY Ha",
      "H:m M D YYYY",
      "H:ma M D YYYY",
      "H:mA M D YYYY",
      "M D YYYY H:m",
      "M D YYYY H:ma",
      "M D YYYY H:mA",
      "MMM D YYYY",
      "HA MMM D YYYY",
      "Ha MMM D YYYY",
      "MMM D YYYY HA",
      "MMM D YYYY Ha",
      "H:m MMM D YYYY",
      "H:ma MMM D YYYY",
      "H:mA MMM D YYYY",
      "MMM D YYYY H:m",
      "MMM D YYYY H:ma",
      "MMM D YYYY H:mA",
      "ddd",
      "dddd",
      "HA",
      "Ha",
      "H:m",
      "H:mA",
      "H:ma",
      "HA ddd",
      "HA dddd",
      "Ha ddd",
      "Ha dddd",
      "H:m ddd",
      "H:ma ddd",
      "H:mA ddd",
      "H:m dddd",
      "H:ma dddd",
      "H:mA dddd",
      "ddd HA",
      "ddd Ha",
      "ddd H:m",
      "ddd H:ma",
      "ddd H:mA",
      "dddd HA",
      "dddd Ha",
      "dddd H:m",
      "dddd H:ma",
      "dddd H:mA",
    ],
    true
  );
}

export function validateTimeInput(str) {
  str = str.trim();

  return moment(str, ["HA", "Ha", "H:m", "H:mA", "H:ma"], true);
}
